language: node_js
node_js:
  - 14
cache:
  directories:
    - ~/.npm
notifications:
  email: false
branches:
  only:
    - master
jobs:
  include:
    - stage: release
      node_js: 14
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
